package mx.com.mesaregia.logistica.application.service.impl;
import mx.com.mesaregia.logistica.api.request.*; import mx.com.mesaregia.logistica.api.response.VehiculoResponse; import mx.com.mesaregia.logistica.application.service.VehiculoService; import mx.com.mesaregia.logistica.domain.entity.Vehiculo; import mx.com.mesaregia.logistica.exception.*; import mx.com.mesaregia.logistica.mapper.LogisticaMapper; import mx.com.mesaregia.logistica.repository.VehiculoRepository; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class VehiculoServiceImpl implements VehiculoService {private final VehiculoRepository repo;private final LogisticaMapper map;public VehiculoServiceImpl(VehiculoRepository r,LogisticaMapper m){repo=r;map=m;}
 @Transactional(readOnly=true) public List<VehiculoResponse> listar(){return repo.findAllByActivoTrueOrderByPlacaAsc().stream().map(map::vehiculo).toList();}
 @Transactional public VehiculoResponse crear(VehiculoCreateRequest r){String p=r.placa().trim().toUpperCase(Locale.ROOT);if(repo.findByPlacaIgnoreCase(p).isPresent())throw new ConflictException("La placa ya existe");var v=new Vehiculo();v.setPlaca(p);v.setActivo(true);return map.vehiculo(repo.saveAndFlush(v));}
 @Transactional public VehiculoResponse actualizar(Long id,VehiculoUpdateRequest r){var v=get(id);ServiceSupport.version(v.getVersion(),r.version());String p=r.placa().trim().toUpperCase(Locale.ROOT);repo.findByPlacaIgnoreCase(p).filter(x->!x.getId().equals(id)).ifPresent(x->{throw new ConflictException("La placa ya existe");});v.setPlaca(p);return map.vehiculo(repo.saveAndFlush(v));}
 @Transactional public VehiculoResponse estado(Long id,VehiculoEstadoRequest r){var v=get(id);ServiceSupport.version(v.getVersion(),r.version());v.setActivo(r.activo());return map.vehiculo(repo.saveAndFlush(v));}
 private Vehiculo get(Long id){return repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Vehículo no encontrado"));}
}
