ALTER TABLE orden_servicio DROP CONSTRAINT ck_orden_estado;
ALTER TABLE orden_servicio MODIFY estado VARCHAR(30) NOT NULL DEFAULT 'EN_REVISION_VENTAS';
ALTER TABLE orden_servicio ADD CONSTRAINT ck_orden_estado CHECK (estado IN ('EN_REVISION_VENTAS','PENDIENTE_PROGRAMACION','PROGRAMADA','EN_EJECUCION','REALIZADA','CANCELADA'));

ALTER TABLE historial_estado_orden DROP CONSTRAINT ck_historial_orden_estado;
ALTER TABLE historial_estado_orden ADD CONSTRAINT ck_historial_orden_estado CHECK (estado_nuevo IN ('EN_REVISION_VENTAS','PENDIENTE_PROGRAMACION','PROGRAMADA','EN_EJECUCION','REALIZADA','CANCELADA'));
