package mx.com.mesaregia.seguridad.application.service.impl;
import com.fasterxml.jackson.core.JsonProcessingException; import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor; import mx.com.mesaregia.seguridad.api.response.*; import mx.com.mesaregia.seguridad.application.service.AuditoriaService; import mx.com.mesaregia.seguridad.domain.entity.*; import mx.com.mesaregia.seguridad.domain.enums.ResultadoAuditoria; import mx.com.mesaregia.seguridad.mapper.AuditoriaMapper; import mx.com.mesaregia.seguridad.repository.*;
import org.slf4j.MDC; import org.springframework.data.domain.Pageable; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.*; import java.time.LocalDateTime;
@Service @RequiredArgsConstructor public class AuditoriaServiceImpl implements AuditoriaService {
 private final EventoAuditoriaRepository repo; private final UsuarioRepository usuarios; private final AuditoriaMapper mapper; private final ObjectMapper objectMapper;
 @Override @Transactional(readOnly=true) public PageResponse<AuditoriaResponse> buscar(LocalDateTime d,LocalDateTime h,Long u,String m,String a,String c,Pageable p){return PageResponse.from(repo.buscar(d,h,u,blank(m),blank(a),blank(c),p).map(mapper::toResponse));}
 @Override @Transactional(propagation=Propagation.MANDATORY) public void registrar(String modulo,String accion,String tipo,String identificador,String motivo,Object anterior,Object nuevo,String detalle){ EventoAuditoria e=new EventoAuditoria(); e.setModulo(modulo);e.setAccion(accion);e.setTipoRecurso(tipo);e.setIdentificadorRecurso(identificador);e.setResultado(ResultadoAuditoria.EXITOSO);e.setMotivo(motivo);e.setValorAnterior(json(anterior));e.setValorNuevo(json(nuevo));e.setDetalle(detalle);e.setIdCorrelacion(MDC.get("correlationId")); var auth=SecurityContextHolder.getContext().getAuthentication(); if(auth!=null&&auth.isAuthenticated()&&!"anonymousUser".equals(auth.getName())) usuarios.findByIdentificador(auth.getName()).ifPresent(e::setUsuario); repo.save(e); }
 private String json(Object o){if(o==null)return null;try{return objectMapper.writeValueAsString(o);}catch(JsonProcessingException ex){return "{"serialization":"unavailable"}";}}
 private String blank(String s){return s==null||s.isBlank()?null:s;}
}
