package mx.com.mesaregia.pagos.application.service.impl;
import mx.com.mesaregia.pagos.application.service.PagoCoverageService; import mx.com.mesaregia.pagos.config.CorrelationIdFilter; import mx.com.mesaregia.pagos.domain.entity.*; import mx.com.mesaregia.pagos.domain.enums.*; import mx.com.mesaregia.pagos.integration.event.*; import mx.com.mesaregia.pagos.repository.*; import org.slf4j.MDC; import org.springframework.stereotype.Service; import org.springframework.transaction.support.*; import java.math.BigDecimal; import java.time.OffsetDateTime;
@Service public class PagoCoverageServiceImpl implements PagoCoverageService {
 private final CuentaCobroCalculator calc; private final CuentaCobroRepository cuentas; private final MovimientoCuentaRepository movs; private final FolioService folios; private final DomainEventPublisher publisher;
 public PagoCoverageServiceImpl(CuentaCobroCalculator c,CuentaCobroRepository cr,MovimientoCuentaRepository mr,FolioService f,DomainEventPublisher p){calc=c;cuentas=cr;movs=mr;folios=f;publisher=p;}
 @Override public boolean evaluarYPublicar(CuentaCobro cuenta,Pago pago){var t=calc.calcular(cuenta);actualizarEstado(cuenta,t);boolean nuevo=false;if(t.acumuladoNeto().compareTo(t.importeRequerido())>=0&&!movs.existsByCuentaCobroIdAndTipoMovimiento(cuenta.getId(),TipoMovimientoCuenta.CONFIRMACION)){var m=new MovimientoCuenta();m.setCuentaCobro(cuenta);m.setPago(pago);m.setFolio(folios.generar("MOV"));m.setTipoMovimiento(TipoMovimientoCuenta.CONFIRMACION);m.setNaturaleza(NaturalezaMovimiento.NEUTRO);m.setMonto(BigDecimal.ZERO);m.setOperacionExterna("IMPORTE_REQUERIDO_CUBIERTO");m.setResultado("PENDIENTE");m.setDescripcion("Umbral de confirmación cubierto; entrega pendiente al adapter de integración");m.setClaveOperacion("COVERAGE:"+cuenta.getId());movs.saveAndFlush(m);nuevo=true;String corr=MDC.get(CorrelationIdFilter.MDC_KEY);var ev=new ImporteRequeridoCubiertoEvent(cuenta.getId(),cuenta.getIdCotizacionExterno(),cuenta.getIdCotizacionVersionExterno(),t.acumuladoNeto(),t.importeRequerido(),corr,OffsetDateTime.now());afterCommit(()->publisher.publish(ev));}return nuevo;}
 @Override public void recalcularSinPublicar(CuentaCobro c){actualizarEstado(c,calc.calcular(c));}
 private void actualizarEstado(CuentaCobro c,CuentaCobroCalculator.Totales t){if(c.getEstado()==EstadoCuentaCobro.CANCELADA)return;EstadoCuentaCobro e=t.acumuladoNeto().compareTo(c.getImporteTotal())>=0?EstadoCuentaCobro.LIQUIDADA:t.acumuladoNeto().compareTo(t.importeRequerido())>=0?EstadoCuentaCobro.CONFIRMACION_CUBIERTA:EstadoCuentaCobro.ABIERTA;if(e!=c.getEstado()){c.setEstado(e);cuentas.saveAndFlush(c);}}
 private void afterCommit(Runnable r){if(TransactionSynchronizationManager.isActualTransactionActive()){TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization(){@Override public void afterCommit(){r.run();}});}else r.run();}
}
