CREATE TABLE IF NOT EXISTS cuenta_cobro (
  id_cuenta_cobro BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_cotizacion_externo BIGINT UNSIGNED NOT NULL,
  id_cotizacion_version_externo BIGINT UNSIGNED NOT NULL,
  id_cliente_externo BIGINT UNSIGNED NOT NULL,
  folio_cotizacion_snapshot VARCHAR(50) NOT NULL,
  numero_version_snapshot SMALLINT UNSIGNED NOT NULL,
  nombre_cliente_snapshot VARCHAR(300) NOT NULL,
  importe_total DECIMAL(14,2) NOT NULL,
  porcentaje_confirmacion DECIMAL(5,2) NOT NULL,
  estado VARCHAR(30) NOT NULL DEFAULT 'ABIERTA',
  creado_en DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  actualizado_en DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  CONSTRAINT pk_cuenta_cobro PRIMARY KEY (id_cuenta_cobro),
  CONSTRAINT uk_cuenta_cotizacion_version UNIQUE (id_cotizacion_externo,id_cotizacion_version_externo),
  CONSTRAINT ck_cuenta_importe CHECK (importe_total >= 0),
  CONSTRAINT ck_cuenta_porcentaje CHECK (porcentaje_confirmacion >= 0 AND porcentaje_confirmacion <= 100),
  CONSTRAINT ck_cuenta_estado CHECK (estado IN ('ABIERTA','CONFIRMACION_CUBIERTA','LIQUIDADA','CANCELADA')),
  INDEX ix_cuenta_cliente (id_cliente_externo),
  INDEX ix_cuenta_estado (estado)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS pago (
  id_pago BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  folio VARCHAR(40) NOT NULL,
  fecha_pago DATE NOT NULL,
  monto DECIMAL(14,2) NOT NULL,
  metodo_pago VARCHAR(30) NOT NULL,
  referencia_pago VARCHAR(150) NULL,
  observaciones VARCHAR(500) NULL,
  clave_operacion VARCHAR(120) NOT NULL,
  id_usuario_externo BIGINT UNSIGNED NOT NULL,
  fecha_hora_registro DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT pk_pago PRIMARY KEY (id_pago),
  CONSTRAINT uk_pago_folio UNIQUE (folio),
  CONSTRAINT uk_pago_clave_operacion UNIQUE (clave_operacion),
  CONSTRAINT ck_pago_monto CHECK (monto > 0),
  CONSTRAINT ck_pago_metodo CHECK (metodo_pago IN ('EFECTIVO','TRANSFERENCIA')),
  INDEX ix_pago_fecha (fecha_pago),
  INDEX ix_pago_metodo (metodo_pago)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS aplicacion_pago (
  id_aplicacion_pago BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_pago BIGINT UNSIGNED NOT NULL,
  id_cuenta_cobro BIGINT UNSIGNED NOT NULL,
  monto_aplicado DECIMAL(14,2) NOT NULL,
  fecha_hora_aplicacion DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT pk_aplicacion_pago PRIMARY KEY (id_aplicacion_pago),
  CONSTRAINT fk_aplicacion_pago FOREIGN KEY (id_pago) REFERENCES pago(id_pago),
  CONSTRAINT fk_aplicacion_cuenta FOREIGN KEY (id_cuenta_cobro) REFERENCES cuenta_cobro(id_cuenta_cobro),
  CONSTRAINT ck_aplicacion_monto CHECK (monto_aplicado > 0),
  INDEX ix_aplicacion_cuenta (id_cuenta_cobro),
  INDEX ix_aplicacion_pago (id_pago)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS movimiento_cuenta (
  id_movimiento_cuenta BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_cuenta_cobro BIGINT UNSIGNED NOT NULL,
  id_pago BIGINT UNSIGNED NULL,
  id_movimiento_origen BIGINT UNSIGNED NULL,
  folio VARCHAR(50) NOT NULL,
  tipo_movimiento VARCHAR(40) NOT NULL,
  naturaleza VARCHAR(10) NOT NULL,
  monto DECIMAL(14,2) NOT NULL DEFAULT 0,
  operacion_externa VARCHAR(80) NULL,
  referencia_externa VARCHAR(150) NULL,
  resultado VARCHAR(30) NULL,
  descripcion VARCHAR(1000) NULL,
  fecha_hora DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  id_usuario_externo BIGINT UNSIGNED NULL,
  clave_operacion VARCHAR(120) NULL,
  CONSTRAINT pk_movimiento_cuenta PRIMARY KEY (id_movimiento_cuenta),
  CONSTRAINT uk_movimiento_cuenta_folio UNIQUE (folio),
  CONSTRAINT uk_movimiento_cuenta_clave UNIQUE (clave_operacion),
  CONSTRAINT fk_movimiento_cuenta FOREIGN KEY (id_cuenta_cobro) REFERENCES cuenta_cobro(id_cuenta_cobro),
  CONSTRAINT fk_movimiento_pago FOREIGN KEY (id_pago) REFERENCES pago(id_pago),
  CONSTRAINT fk_movimiento_origen FOREIGN KEY (id_movimiento_origen) REFERENCES movimiento_cuenta(id_movimiento_cuenta),
  CONSTRAINT ck_movimiento_tipo CHECK (tipo_movimiento IN ('PAGO','COMPENSACION','CORRECCION','CONFIRMACION','FALLO_INTEGRACION')),
  CONSTRAINT ck_movimiento_naturaleza CHECK (naturaleza IN ('CARGO','ABONO','NEUTRO')),
  CONSTRAINT ck_movimiento_monto CHECK (monto >= 0),
  CONSTRAINT ck_movimiento_neutro CHECK ((naturaleza='NEUTRO' AND monto=0) OR naturaleza<>'NEUTRO'),
  INDEX ix_movimiento_cuenta_fecha (id_cuenta_cobro,fecha_hora),
  INDEX ix_movimiento_tipo_fecha (tipo_movimiento,fecha_hora)
) ENGINE=InnoDB;
