-- Baseline aprobada de mr_seguridad (MariaDB 12.3.3)
CREATE TABLE IF NOT EXISTS rol (id_rol BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,codigo VARCHAR(40) NOT NULL,nombre VARCHAR(100) NOT NULL,descripcion VARCHAR(250) NULL,activo TINYINT(1) NOT NULL DEFAULT 1,creado_en DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),actualizado_en DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),version BIGINT UNSIGNED NOT NULL DEFAULT 1,CONSTRAINT pk_rol PRIMARY KEY(id_rol),CONSTRAINT uk_rol_codigo UNIQUE(codigo),CONSTRAINT ck_rol_activo CHECK(activo IN(0,1))) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS permiso (id_permiso BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,codigo VARCHAR(120) NOT NULL,modulo VARCHAR(80) NOT NULL,accion VARCHAR(100) NOT NULL,descripcion VARCHAR(250) NULL,activo TINYINT(1) NOT NULL DEFAULT 1,creado_en DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),actualizado_en DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),version BIGINT UNSIGNED NOT NULL DEFAULT 1,CONSTRAINT pk_permiso PRIMARY KEY(id_permiso),CONSTRAINT uk_permiso_codigo UNIQUE(codigo),CONSTRAINT ck_permiso_activo CHECK(activo IN(0,1))) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS rol_permiso_alcance (id_rol_permiso_alcance BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,id_rol BIGINT UNSIGNED NOT NULL,id_permiso BIGINT UNSIGNED NOT NULL,alcance VARCHAR(100) NOT NULL DEFAULT 'General',activo TINYINT(1) NOT NULL DEFAULT 1,creado_en DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),actualizado_en DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),version BIGINT UNSIGNED NOT NULL DEFAULT 1,CONSTRAINT pk_rol_permiso_alcance PRIMARY KEY(id_rol_permiso_alcance),CONSTRAINT uk_rol_permiso_alcance UNIQUE(id_rol,id_permiso,alcance),CONSTRAINT fk_rpa_rol FOREIGN KEY(id_rol) REFERENCES rol(id_rol),CONSTRAINT fk_rpa_permiso FOREIGN KEY(id_permiso) REFERENCES permiso(id_permiso),CONSTRAINT ck_rpa_activo CHECK(activo IN(0,1))) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS usuario (id_usuario BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,nombre VARCHAR(150) NOT NULL,identificador VARCHAR(150) NOT NULL,id_rol BIGINT UNSIGNED NOT NULL,activo TINYINT(1) NOT NULL DEFAULT 1,ultimo_acceso_en DATETIME(6) NULL,creado_en DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),actualizado_en DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),version BIGINT UNSIGNED NOT NULL DEFAULT 1,CONSTRAINT pk_usuario PRIMARY KEY(id_usuario),CONSTRAINT uk_usuario_identificador UNIQUE(identificador),CONSTRAINT fk_usuario_rol FOREIGN KEY(id_rol) REFERENCES rol(id_rol),CONSTRAINT ck_usuario_activo CHECK(activo IN(0,1)),INDEX ix_usuario_rol(id_rol),INDEX ix_usuario_activo(activo),INDEX ix_usuario_nombre(nombre)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS configuracion_sistema (id_configuracion BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,clave VARCHAR(100) NOT NULL,nombre VARCHAR(150) NOT NULL,descripcion VARCHAR(500) NULL,tipo_dato VARCHAR(30) NOT NULL,valor TEXT NULL,activo TINYINT(1) NOT NULL DEFAULT 1,creado_en DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),actualizado_en DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),version BIGINT UNSIGNED NOT NULL DEFAULT 1,CONSTRAINT pk_configuracion_sistema PRIMARY KEY(id_configuracion),CONSTRAINT uk_configuracion_sistema_clave UNIQUE(clave),CONSTRAINT ck_configuracion_tipo CHECK(tipo_dato IN('TEXTO','ENTERO','DECIMAL','BOOLEANO','FECHA')),CONSTRAINT ck_configuracion_activo CHECK(activo IN(0,1))) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS evento_auditoria (id_evento_auditoria BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,fecha_hora DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),id_usuario BIGINT UNSIGNED NULL,modulo VARCHAR(80) NOT NULL,accion VARCHAR(100) NOT NULL,tipo_recurso VARCHAR(100) NULL,identificador_recurso VARCHAR(150) NULL,resultado VARCHAR(30) NOT NULL,motivo VARCHAR(500) NULL,valor_anterior LONGTEXT NULL,valor_nuevo LONGTEXT NULL,detalle LONGTEXT NULL,id_correlacion VARCHAR(100) NULL,CONSTRAINT pk_evento_auditoria PRIMARY KEY(id_evento_auditoria),CONSTRAINT fk_evento_auditoria_usuario FOREIGN KEY(id_usuario) REFERENCES usuario(id_usuario),CONSTRAINT ck_evento_auditoria_resultado CHECK(resultado IN('EXITOSO','RECHAZADO','ERROR')),INDEX ix_auditoria_fecha(fecha_hora),INDEX ix_auditoria_usuario_fecha(id_usuario,fecha_hora),INDEX ix_auditoria_modulo_accion_fecha(modulo,accion,fecha_hora),INDEX ix_auditoria_recurso(tipo_recurso,identificador_recurso),INDEX ix_auditoria_correlacion(id_correlacion)) ENGINE=InnoDB;

INSERT INTO rol(codigo,nombre,descripcion,activo) VALUES
('ADMIN','Administrador del sistema','Gestión total',1),
('INVENTARIO','Responsable de Inventario','Manejo inventario',1),
('USER','Ventas','Ejecutivo de ventas',1),
('ADMINISTRATIVO','Administrativo','Soporte y registro administrativo',1),
('TECH','Técnico','Soporte técnico y ejecución',1),
('SUPERVISOR','Supervisor','Supervisión de operaciones',1),
('REPRESENTANTE','Representante','Ejecución y seguimiento de actividades logísticas',1),
('CHOFER','Chófer','Operación de traslados logísticos',1),
('DIRECCION','Dirección','Gerencia y dirección ejecutiva',1)
ON DUPLICATE KEY UPDATE nombre=VALUES(nombre),descripcion=VALUES(descripcion),activo=VALUES(activo);

INSERT INTO permiso(codigo,modulo,accion,activo) VALUES
('administracion.consultar','Administración','Consultar',1),
('alertas.asignadas','Alertas','Consultar asignadas',1),
('alertas.consultar','Alertas','Consultar',1),
('auditoria.consultar','Administración','Consultar',1),
('catalogo.auxiliares.gestionar','Catálogo','Gestionar',1),
('catalogo.consultar','Catálogo','Consultar',1),
('catalogo.paquetes.desactivar','Catálogo','Activar/desactivar',1),
('catalogo.paquetes.modificar','Catálogo','Modificar',1),
('catalogo.paquetes.registrar','Catálogo','Registrar',1),
('catalogo.precios.gestionar','Catálogo','Gestionar',1),
('catalogo.productos.desactivar','Catálogo','Activar/desactivar',1),
('catalogo.productos.modificar','Catálogo','Modificar',1),
('catalogo.productos.registrar','Catálogo','Registrar',1),
('catalogo.servicios.desactivar','Catálogo','Activar/desactivar',1),
('catalogo.servicios.modificar','Catálogo','Modificar',1),
('catalogo.servicios.registrar','Catálogo','Registrar',1),
('clientes.buscar','Clientes y prospectos','Buscar',1),
('clientes.clasificar','Clientes y prospectos','Clasificar',1),
('clientes.consultar','Clientes y prospectos','Consultar',1),
('clientes.modificar','Clientes y prospectos','Modificar',1),
('clientes.registrar','Clientes y prospectos','Registrar',1),
('configuracion.consultar','Administración','Consultar',1),
('configuracion.modificar','Administración','Modificar',1),
('cotizaciones.consultar','Cotizaciones','Consultar',1),
('cotizaciones.gestionar','Cotizaciones','Gestionar',1),
('dashboard.consultar','Panel principal','Consultar',1),
('documentacion.tecnica.consultar','Administración','Consultar',1),
('intercambio.exportar','Administración','Exportar',1),
('intercambio.importar','Administración','Importar',1),
('intercambio.validar','Administración','Validar',1),
('inventario.alertas.consultar','Inventario','Consultar',1),
('inventario.consultar','Inventario','Consultar',1),
('inventario.cortes.consultar','Inventario','Consultar',1),
('inventario.cortes.gestionar','Inventario','Gestionar',1),
('inventario.disponibilidad.consultar','Inventario','Consultar',1),
('inventario.existencias.inactivos.consultar','Inventario','Consultar',1),
('inventario.existencias.operativas.consultar','Inventario','Consultar',1),
('inventario.gestionar','Inventario','Gestionar',1),
('inventario.movimientos.consultar','Inventario','Consultar',1),
('inventario.reservas.consultar','Inventario','Consultar',1),
('logistica.asignadas','Logística','Consultar asignadas',1),
('logistica.consultar','Logística','Consultar',1),
('logistica.gestionar','Logística','Gestionar',1),
('logistica.proceso.gestion','Logística','Gestion',1),
('logistica.tolerancias.gestionar','Logística','Gestionar',1),
('logistica.traslado','Logística','Traslado',1),
('matriz.consultar','Administración','Consultar',1),
('ordenes.asignadas','Órdenes de servicio','Consultar asignadas',1),
('ordenes.cancelar','Órdenes de servicio','Cancelar',1),
('ordenes.consultar','Órdenes de servicio','Consultar',1),
('ordenes.detalle.consultar','Órdenes de servicio','Consultar',1),
('ordenes.inventario.consultar','Órdenes de servicio','Consultar',1),
('ordenes.logistica.consultar','Órdenes de servicio','Consultar',1),
('ordenes.origen-cotizacion.consultar','Órdenes de servicio','Consultar',1),
('ordenes.revisar','Órdenes de servicio','Revisar',1),
('pagos.alertas.consultar','Pagos manuales','Consultar',1),
('pagos.consultar','Pagos manuales','Consultar',1),
('pagos.gestionar','Pagos manuales','Gestionar',1),
('permisos.consultar','Administración','Consultar',1),
('permisos.modificar','Administración','Modificar',1),
('reportes.consultar','Reportes','Consultar',1),
('roles.consultar','Administración','Consultar',1),
('usuarios.consultar','Administración','Consultar',1),
('usuarios.desactivar','Administración','Activar/desactivar',1),
('usuarios.modificar','Administración','Modificar',1),
('usuarios.password.restablecer','Administración','Restablecer',1),
('usuarios.registrar','Administración','Registrar',1),
('usuarios.rol.asignar','Administración','Asignar',1)
ON DUPLICATE KEY UPDATE modulo=VALUES(modulo),accion=VALUES(accion),activo=VALUES(activo);

CREATE TEMPORARY TABLE tmp_rol_permiso(codigo_rol VARCHAR(40) NOT NULL,codigo_permiso VARCHAR(120) NOT NULL,alcance VARCHAR(100) NOT NULL);
INSERT INTO tmp_rol_permiso(codigo_rol,codigo_permiso,alcance) VALUES
('ADMIN','dashboard.consultar','General'),
('ADMIN','administracion.consultar','General'),
('ADMIN','usuarios.consultar','General'),
('ADMIN','usuarios.registrar','General'),
('ADMIN','usuarios.modificar','General'),
('ADMIN','usuarios.desactivar','General'),
('ADMIN','usuarios.password.restablecer','General'),
('ADMIN','usuarios.rol.asignar','General'),
('ADMIN','roles.consultar','General'),
('ADMIN','permisos.consultar','General'),
('ADMIN','permisos.modificar','General'),
('ADMIN','matriz.consultar','General'),
('ADMIN','auditoria.consultar','General'),
('ADMIN','configuracion.consultar','General'),
('ADMIN','configuracion.modificar','General'),
('ADMIN','intercambio.validar','General'),
('ADMIN','intercambio.importar','General'),
('ADMIN','intercambio.exportar','General'),
('ADMIN','documentacion.tecnica.consultar','General'),
('ADMIN','clientes.consultar','General'),
('ADMIN','clientes.buscar','General'),
('ADMIN','catalogo.consultar','General'),
('ADMIN','catalogo.productos.registrar','General'),
('ADMIN','catalogo.productos.modificar','General'),
('ADMIN','catalogo.productos.desactivar','General'),
('ADMIN','catalogo.servicios.registrar','General'),
('ADMIN','catalogo.servicios.modificar','General'),
('ADMIN','catalogo.servicios.desactivar','General'),
('ADMIN','catalogo.paquetes.registrar','General'),
('ADMIN','catalogo.paquetes.modificar','General'),
('ADMIN','catalogo.paquetes.desactivar','General'),
('ADMIN','catalogo.auxiliares.gestionar','General'),
('ADMIN','catalogo.precios.gestionar','General'),
('ADMIN','inventario.consultar','General'),
('ADMIN','inventario.gestionar','General'),
('ADMIN','inventario.existencias.operativas.consultar','General'),
('ADMIN','inventario.existencias.inactivos.consultar','General'),
('ADMIN','inventario.cortes.consultar','General'),
('ADMIN','inventario.disponibilidad.consultar','General'),
('ADMIN','inventario.reservas.consultar','General'),
('ADMIN','inventario.alertas.consultar','General'),
('ADMIN','cotizaciones.consultar','General'),
('ADMIN','ordenes.consultar','General'),
('ADMIN','ordenes.detalle.consultar','General'),
('ADMIN','ordenes.origen-cotizacion.consultar','General'),
('ADMIN','ordenes.inventario.consultar','General'),
('ADMIN','ordenes.logistica.consultar','General'),
('ADMIN','logistica.consultar','General'),
('ADMIN','logistica.tolerancias.gestionar','General'),
('ADMIN','pagos.consultar','General'),
('ADMIN','pagos.alertas.consultar','General'),
('ADMIN','reportes.consultar','General'),
('ADMIN','alertas.consultar','General'),
('INVENTARIO','dashboard.consultar','General'),
('INVENTARIO','catalogo.consultar','General'),
('INVENTARIO','catalogo.productos.registrar','General'),
('INVENTARIO','catalogo.productos.modificar','General'),
('INVENTARIO','catalogo.productos.desactivar','General'),
('INVENTARIO','catalogo.servicios.registrar','General'),
('INVENTARIO','catalogo.servicios.modificar','General'),
('INVENTARIO','catalogo.servicios.desactivar','General'),
('INVENTARIO','catalogo.paquetes.registrar','General'),
('INVENTARIO','catalogo.paquetes.modificar','General'),
('INVENTARIO','catalogo.paquetes.desactivar','General'),
('INVENTARIO','catalogo.auxiliares.gestionar','General'),
('INVENTARIO','catalogo.precios.gestionar','General'),
('INVENTARIO','inventario.consultar','General'),
('INVENTARIO','inventario.gestionar','General'),
('INVENTARIO','inventario.disponibilidad.consultar','General'),
('INVENTARIO','inventario.reservas.consultar','General'),
('INVENTARIO','inventario.existencias.operativas.consultar','General'),
('INVENTARIO','inventario.existencias.inactivos.consultar','General'),
('INVENTARIO','inventario.cortes.consultar','General'),
('INVENTARIO','inventario.cortes.gestionar','General'),
('INVENTARIO','inventario.alertas.consultar','General'),
('INVENTARIO','inventario.movimientos.consultar','General'),
('INVENTARIO','ordenes.consultar','General'),
('INVENTARIO','ordenes.detalle.consultar','General'),
('INVENTARIO','ordenes.inventario.consultar','General'),
('INVENTARIO','ordenes.logistica.consultar','General'),
('INVENTARIO','logistica.consultar','General'),
('INVENTARIO','reportes.consultar','General'),
('INVENTARIO','alertas.consultar','General'),
('USER','dashboard.consultar','General'),
('USER','clientes.consultar','General'),
('USER','clientes.buscar','General'),
('USER','clientes.registrar','General'),
('USER','clientes.modificar','General'),
('USER','catalogo.consultar','General'),
('USER','inventario.consultar','General'),
('USER','inventario.disponibilidad.consultar','General'),
('USER','inventario.reservas.consultar','General'),
('USER','cotizaciones.consultar','General'),
('USER','cotizaciones.gestionar','General'),
('USER','ordenes.consultar','General'),
('USER','ordenes.detalle.consultar','General'),
('USER','ordenes.revisar','General'),
('USER','ordenes.cancelar','General'),
('USER','ordenes.origen-cotizacion.consultar','General'),
('USER','ordenes.inventario.consultar','General'),
('USER','ordenes.logistica.consultar','General'),
('USER','logistica.consultar','General'),
('USER','reportes.consultar','General'),
('USER','alertas.consultar','General'),
('ADMINISTRATIVO','dashboard.consultar','General'),
('ADMINISTRATIVO','clientes.consultar','General'),
('ADMINISTRATIVO','clientes.buscar','General'),
('ADMINISTRATIVO','clientes.registrar','General'),
('ADMINISTRATIVO','clientes.modificar','General'),
('ADMINISTRATIVO','catalogo.consultar','General'),
('ADMINISTRATIVO','inventario.consultar','General'),
('ADMINISTRATIVO','inventario.disponibilidad.consultar','General'),
('ADMINISTRATIVO','inventario.reservas.consultar','General'),
('ADMINISTRATIVO','inventario.alertas.consultar','General'),
('ADMINISTRATIVO','inventario.movimientos.consultar','General'),
('ADMINISTRATIVO','cotizaciones.consultar','General'),
('ADMINISTRATIVO','cotizaciones.gestionar','General'),
('ADMINISTRATIVO','ordenes.consultar','General'),
('ADMINISTRATIVO','ordenes.detalle.consultar','General'),
('ADMINISTRATIVO','ordenes.origen-cotizacion.consultar','General'),
('ADMINISTRATIVO','ordenes.inventario.consultar','General'),
('ADMINISTRATIVO','ordenes.logistica.consultar','General'),
('ADMINISTRATIVO','logistica.consultar','General'),
('ADMINISTRATIVO','logistica.tolerancias.gestionar','General'),
('ADMINISTRATIVO','pagos.consultar','General'),
('ADMINISTRATIVO','pagos.gestionar','General'),
('ADMINISTRATIVO','pagos.alertas.consultar','General'),
('ADMINISTRATIVO','reportes.consultar','General'),
('ADMINISTRATIVO','alertas.consultar','General'),
('TECH','dashboard.consultar','General'),
('TECH','catalogo.consultar','General'),
('TECH','ordenes.asignadas','Órdenes asignadas'),
('TECH','ordenes.logistica.consultar','General'),
('TECH','alertas.consultar','Asignadas'),
('TECH','alertas.asignadas','Asignadas'),
('SUPERVISOR','dashboard.consultar','General'),
('SUPERVISOR','clientes.consultar','General'),
('SUPERVISOR','clientes.buscar','General'),
('SUPERVISOR','clientes.clasificar','General'),
('SUPERVISOR','catalogo.consultar','General'),
('SUPERVISOR','inventario.consultar','General'),
('SUPERVISOR','inventario.disponibilidad.consultar','General'),
('SUPERVISOR','inventario.reservas.consultar','General'),
('SUPERVISOR','inventario.existencias.operativas.consultar','General'),
('SUPERVISOR','inventario.existencias.inactivos.consultar','General'),
('SUPERVISOR','inventario.cortes.consultar','General'),
('SUPERVISOR','inventario.alertas.consultar','General'),
('SUPERVISOR','cotizaciones.consultar','General'),
('SUPERVISOR','ordenes.consultar','General'),
('SUPERVISOR','ordenes.detalle.consultar','General'),
('SUPERVISOR','ordenes.origen-cotizacion.consultar','General'),
('SUPERVISOR','ordenes.inventario.consultar','General'),
('SUPERVISOR','ordenes.logistica.consultar','General'),
('SUPERVISOR','logistica.consultar','General'),
('SUPERVISOR','logistica.gestionar','General'),
('SUPERVISOR','pagos.consultar','General'),
('SUPERVISOR','reportes.consultar','General'),
('SUPERVISOR','alertas.consultar','General'),
('REPRESENTANTE','dashboard.consultar','General'),
('REPRESENTANTE','logistica.asignadas','Asignaciones propias'),
('REPRESENTANTE','logistica.proceso.gestion','Fases asignadas'),
('REPRESENTANTE','logistica.traslado','Traslados asignados'),
('REPRESENTANTE','alertas.consultar','Asignadas'),
('REPRESENTANTE','alertas.asignadas','Asignadas'),
('CHOFER','dashboard.consultar','General'),
('CHOFER','logistica.asignadas','Asignaciones propias'),
('CHOFER','logistica.traslado','Traslados asignados'),
('CHOFER','alertas.consultar','Asignadas'),
('CHOFER','alertas.asignadas','Asignadas'),
('DIRECCION','dashboard.consultar','General'),
('DIRECCION','catalogo.consultar','General'),
('DIRECCION','inventario.consultar','General'),
('DIRECCION','inventario.alertas.consultar','General'),
('DIRECCION','inventario.movimientos.consultar','General'),
('DIRECCION','cotizaciones.consultar','General'),
('DIRECCION','ordenes.consultar','General'),
('DIRECCION','ordenes.detalle.consultar','General'),
('DIRECCION','ordenes.origen-cotizacion.consultar','General'),
('DIRECCION','ordenes.logistica.consultar','General'),
('DIRECCION','logistica.consultar','General'),
('DIRECCION','pagos.consultar','General'),
('DIRECCION','reportes.consultar','General'),
('DIRECCION','alertas.consultar','General');
INSERT INTO rol_permiso_alcance(id_rol,id_permiso,alcance,activo) SELECT r.id_rol,p.id_permiso,t.alcance,1 FROM tmp_rol_permiso t JOIN rol r ON r.codigo=t.codigo_rol JOIN permiso p ON p.codigo=t.codigo_permiso ON DUPLICATE KEY UPDATE activo=1;
DROP TEMPORARY TABLE tmp_rol_permiso;
