spring:
  application:
    name: mr-reportes-service
  profiles:
    default: local

server:
  port: ${SERVER_PORT:8089}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: prod
