package mx.com.mesaregia.inventario.application.service.impl;
import mx.com.mesaregia.inventario.application.service.CorteFisicoService; import mx.com.mesaregia.inventario.api.request.*; import mx.com.mesaregia.inventario.api.response.*; import mx.com.mesaregia.inventario.domain.entity.*; import mx.com.mesaregia.inventario.domain.enums.EstadoCorte; import mx.com.mesaregia.inventario.exception.*; import mx.com.mesaregia.inventario.mapper.InventarioMapper; import mx.com.mesaregia.inventario.repository.*; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.Objects;
@Service
public class CorteFisicoServiceImpl implements CorteFisicoService {
 private final CorteFisicoRepository cr; private final CorteDetalleRepository dr; private final ExistenciaRepository er; private final InventorySupport support; public CorteFisicoServiceImpl(CorteFisicoRepository c,CorteDetalleRepository d,ExistenciaRepository e,InventorySupport s){cr=c;dr=d;er=e;support=s;}
 @Override @Transactional public CorteResponse iniciar(CorteIniciarRequest q){var exist=er.findAllByAlmacenIdOrderByIdProductoExterno(q.idAlmacen());if(exist.isEmpty())throw new BusinessRuleException("No existen registros de inventario para iniciar el corte");var c=new CorteFisico();c.setFolio(support.folio("CORTE"));c.setAlmacen(support.almacen(q.idAlmacen()));c.setEstado(EstadoCorte.ABIERTO);c.setIdUsuarioInicioExterno(q.idUsuarioExterno());c.setObservaciones(q.observaciones());c=cr.saveAndFlush(c);for(var e:exist){var d=new CorteDetalle();d.setCorteFisico(c);d.setExistencia(e);d.setCantidadRegistrada(e.getExistenciaFisica());dr.save(d);}dr.flush();return obtener(c.getId());}
 @Override @Transactional public CorteResponse registrarConteos(Long id,CorteConteosRequest q){var c=cr.findForUpdate(id).orElseThrow(()->new ResourceNotFoundException("Corte no encontrado"));if(c.getEstado()!=EstadoCorte.ABIERTO)throw new ConflictException("El corte ya está cerrado");if(!Objects.equals(q.version(),c.getVersion()))throw new ConflictException("El corte fue modificado por otro proceso");for(var x:q.conteos()){var d=dr.findByCorteFisicoIdAndExistenciaId(id,x.idExistencia()).orElseThrow(()->new BusinessRuleException("La existencia no pertenece al corte"));d.setCantidadFisica(x.cantidadFisica());dr.save(d);}dr.flush();return obtener(id);}
 @Override @Transactional public CorteResponse cerrar(Long id,CorteCerrarRequest q){var c=cr.findForUpdate(id).orElseThrow(()->new ResourceNotFoundException("Corte no encontrado"));if(c.getEstado()==EstadoCorte.CERRADO)return InventarioMapper.corte(c);if(!Objects.equals(q.version(),c.getVersion()))throw new ConflictException("El corte fue modificado por otro proceso");if(c.getDetalles().stream().anyMatch(d->d.getCantidadFisica()==null))throw new BusinessRuleException("Todos los productos deben tener conteo físico antes de cerrar");c.setEstado(EstadoCorte.CERRADO);c.setFechaHoraCierre(LocalDateTime.now());c.setIdUsuarioCierreExterno(q.idUsuarioExterno());cr.saveAndFlush(c);return obtener(id);}
 @Override @Transactional(readOnly=true) public CorteResponse obtener(Long id){var c=cr.findWithDetailsById(id).orElseThrow(()->new ResourceNotFoundException("Corte no encontrado"));return InventarioMapper.corte(c);}
 @Override @Transactional(readOnly=true) public PageResponse<CorteResponse> buscar(Pageable p){return PageResponse.from(cr.findAllByOrderByIdDesc(p).map(c->new CorteResponse(c.getId(),c.getFolio(),c.getAlmacen().getId(),c.getEstado(),c.getFechaHoraInicio(),c.getFechaHoraCierre(),c.getIdUsuarioInicioExterno(),c.getIdUsuarioCierreExterno(),c.getObservaciones(),c.getVersion(),java.util.List.of())));}
}
