package mx.com.mesaregia.inventario.application.service.impl;
import mx.com.mesaregia.inventario.application.service.ReservaQueryService; import mx.com.mesaregia.inventario.api.response.*; import mx.com.mesaregia.inventario.domain.entity.Reserva; import mx.com.mesaregia.inventario.domain.enums.*; import mx.com.mesaregia.inventario.exception.ResourceNotFoundException; import mx.com.mesaregia.inventario.repository.*; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDate;
@Service public class ReservaQueryServiceImpl implements ReservaQueryService {
 private final ReservaRepository rr; private final MovimientoInventarioRepository mr; public ReservaQueryServiceImpl(ReservaRepository r,MovimientoInventarioRepository m){rr=r;mr=m;}
 private ReservaResponse map(Reserva r){var ds=r.getDetalles().stream().map(d->{long s=0,ret=0;if(r.getIdOrdenExterno()!=null){s=mr.sumCantidad(r.getIdOrdenExterno(),d.getExistencia().getId(),OrigenOperacion.SALIDA_ORDEN);ret=mr.sumCantidad(r.getIdOrdenExterno(),d.getExistencia().getId(),OrigenOperacion.RETORNO_ORDEN);}return new ReservaDetalleResponse(d.getId(),d.getExistencia().getId(),d.getExistencia().getIdProductoExterno(),d.getExistencia().getAlmacen().getId(),d.getCantidadReservada(),Math.toIntExact(s),Math.toIntExact(ret));}).toList();return new ReservaResponse(r.getId(),r.getFolio(),r.getIdOrdenExterno(),r.getEstado(),r.getFechaInicio(),r.getFechaFin(),r.getMotivoCancelacion(),r.getReferenciaSalida(),r.getCreadoEn(),r.getActualizadoEn(),r.getVersion(),ds);}
 @Override @Transactional(readOnly=true) public PageResponse<ReservaResponse> buscar(Long orden,EstadoReserva estado,LocalDate desde,LocalDate hasta,Pageable p){return PageResponse.from(rr.findAll(ReservaSpecifications.filtros(orden,estado,desde,hasta),p).map(this::map));}
 @Override @Transactional(readOnly=true) public ReservaResponse obtener(Long id){return map(rr.findById(id).orElseThrow(()->new ResourceNotFoundException("Reserva no encontrada")));}
 @Override @Transactional(readOnly=true) public ReservaResponse obtenerPorOrden(Long orden){return map(rr.findFirstByIdOrdenExternoOrderByIdDesc(orden).orElseThrow(()->new ResourceNotFoundException("Reserva no encontrada para la Orden")));}
}
